image: gitpod/workspace-flutter
vscode:
  extensions:
    - Dart-Code.dart-code@3.5.1:W6zqgIED1gxtkBH/pbfGXA==
    - Dart-Code.flutter@3.5.1:0FyuzXye7dV19PNst3+Llg==
tasks:
  - init: flutter run --web-port 8080
ports:
  - port: 8080
    onOpen: open-preview
github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addBadge: true
